### PR TITLE
add FileOptionsChanged to UpdateAllocationRequest

### PR DESCRIPTION
**Pull request by devyetii**
Related to 0chain/0chain#2099 and 0chain/gosdk#762

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/allocation-file-options-not-supported-by-some-clients  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/file-options-not-supported-by-some-sdk-clients  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/allocation-file-options-not-supported-by-some-clients  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/file-options-not-supported-by-some-sdk-clients  |
| zwalletcli  | staging  |
| 0chain  | fix/file-options-not-supported-by-some-sdk-clients  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — COMMENTED** [review]
Can we also add some tests for it?

**Comment by devyetii** [comment]
@Kishan-Dhakan Will be added [here](https://github.com/0chain/system_test/issues/529)

**Review by Kishan-Dhakan — APPROVED** [review]

**Pull request merged**
