### PR TITLE
Validator update config tests

### PR DESCRIPTION
**Pull request by Kishan-Dhakan**

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | validator-tests  |
| gosdk  | feat/update_validator_settings  |
| zboxcli  | feat/update_validator_settings  |
| zwalletcli  | staging  |
| 0chain  | lsvalidators  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by stewartie4 — APPROVED** [review]
Nice catch on the missing coverage, happy pending green run

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | validator-tests  |
| gosdk  | staging  |
| zboxcli  | feat/update_validator_settings  |
| zwalletcli  | staging  |
| 0chain  | lsvalidators  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | validator-tests  |
| gosdk  | staging  |
| zboxcli  | feat/update_validator_settings  |
| zwalletcli  | staging  |
| 0chain  | lsvalidators  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
