### PR TITLE
Fix error output len

### PR DESCRIPTION
**Pull request by din-mukhammed**
Fixes expected error output len for [PR#878](https://github.com/0chain/gosdk/pull/878)

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
