### PR TITLE
Tests for blobber not available

### PR DESCRIPTION
**Pull request by Sriep**
Requires and should be merged simultaneously with the following
- 0chain: https://github.com/0chain/0chain/pull/2466
- gosdk: https://github.com/0chain/gosdk/pull/1043
- zbox: https://github.com/0chain/zboxcli/pull/457

### CODE REVIEW

**Comment by Kishan-Dhakan** [comment]
Does it have related PRs in CLIs?

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | not_available  |
| zboxcli  | not_available  |
| zwalletcli  | staging  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | not_available  |
| zboxcli  | not_available  |
| zwalletcli  | staging  |
| 0chain  | not_available  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | not_available  |
| zboxcli  | not_available  |
| zwalletcli  | staging  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | not_available  |
| zboxcli  | not_available  |
| zwalletcli  | sprint-june-5  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | sprint-june-5  |
| zboxcli  | sprint-june-5  |
| zwalletcli  | sprint-june-5  |
| 0chain  | sprint-june-5  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | sprint-june-5  |
| zwalletcli  | sprint-june-5  |
| 0chain  | sprint-june-5  |
| blobber  | fix/cache_allocation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | sprint-june-5  |
| zboxcli  | not_available  |
| zwalletcli  | sprint-june-5  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | not_available  |
| zboxcli  | not_available  |
| zwalletcli  | sprint-june-5  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
