### PR TITLE
Remove blobber pools

### PR DESCRIPTION
**Pull request by Sriep**
Remove all code related to interest pool smart contract and locking tokens.

### Associated PRs (Link as appropriate):
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/471
- system_test: https://github.com/0chain/system_test/pull/286
- zboxcli:
- zwalletcli: https://github.com/0chain/zwalletcli/pull/135
- 0chain: https://github.com/0chain/0chain/pull/1329

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove_interest_pool  |
| gosdk  | remove_interest_pool  |
| zboxcli  | staging  |
| zwalletcli  | remove_interest_pool  |
| 0chain  | remove_interest_pool  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by stewartie4** [comment]
happy to approve the test removal but there looks to be an issue on the code branch preventing a deploy

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove_interest_pool  |
| gosdk  | remove_interest_pool  |
| zboxcli  | staging  |
| zwalletcli  | remove_interest_pool  |
| 0chain  | remove_interest_pool  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Review by Kishan-Dhakan — APPROVED** [review]

**Review by stewartie4 — APPROVED** [review]

**Pull request merged**
