### PR TITLE
fix(zwallet/send): fixec assertion on send cmd

### PR DESCRIPTION
**Pull request by cnlangzi**
## Fixes
- fixed assertion for `zwallet/send` cmd that is changed by https://github.com/0chain/zwalletcli/pull/129

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/print_hash_on_send  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | sculptex-sendtxjson  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/print_hash_on_send  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | sculptex-sendtxjson  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — CHANGES_REQUESTED** [review]
Since json flag is new code, we should add a case to test case for it. I'll add it

**Comment by cnlangzi** [comment]
> Since json flag is new code, we should add a case to test case for it. I'll add it

feel free to improve it, thanks.

**Review by Kishan-Dhakan — APPROVED** [review]

**Pull request merged**
