### PR TITLE
feat(alloc): added name column on allocation

### PR DESCRIPTION
**Pull request by cnlangzi**
## added tests
- create allocation with name
- update allocation with name

## Associated PRs (Link as appropriate):
- 0chain: https://github.com/0chain/0chain/pull/1193
- gosdk: https://github.com/0chain/gosdk/pull/442
- zboxcli: https://github.com/0chain/zboxcli/pull/221

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feat/add_name_on_alloc  |
| gosdk  | feat/add_name_on_alloc  |
| zboxcli  | feat/add_name_on_alloc  |
| zwalletcli  | staging  |
| 0chain  | feat/add_name_on_alloc  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feat/add_name_on_alloc  |
| gosdk  | feat/add_name_on_alloc  |
| zboxcli  | add_name_on_alloc  |
| zwalletcli  | staging  |
| 0chain  | add_name_on_alloc  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by stewartie4 — APPROVED** [review]

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feat/add_name_on_alloc  |
| gosdk  | feat/add_name_on_alloc  |
| zboxcli  | feat/add_name_on_alloc  |
| zwalletcli  | staging  |
| 0chain  | feat/add_name_on_alloc  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
