### PR TITLE
testcase for duplicate dir while no leading slash

### PR DESCRIPTION
**Pull request by princeparmar**
when we try to create duplicate dir without leading slash it should not work.

gosdk required to merge this:
https://github.com/0chain/gosdk/pull/349

linked PRs
- gosdk: https://github.com/0chain/gosdk/pull/350
- zboxcli: https://github.com/0chain/zboxcli/pull/152

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/152-should-not-create-duplicate-dir  |
| gosdk  | bug/issue-441-duplicate-dir-handling  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by stewartie4** [comment]
Thanks @princeparmar happy to merge once there has been a green run of the new tests

**Review by cnlangzi — CHANGES_REQUESTED** [review]
please check why tests fail

**Comment by stewartie4** [comment]
@Kishan-Dhakan these tests are testing new functionality so i don't think FIXMEs should be added - if the new code doesn't work then it should be fixed before this can merge

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/152-should-not-create-duplicate-dir  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | createDirPatch  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/152-should-not-create-duplicate-dir  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | createDirPatch  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by Kishan-Dhakan** [comment]
@cnlangzi @stewartie4 I've added commits to this PR and opened the following PRs:
- Gosdk: https://github.com/0chain/gosdk/pull/352
- zboxcli: https://github.com/0chain/zboxcli/pull/152

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/152-should-not-create-duplicate-dir  |
| gosdk  | createDirErrorHandling  |
| zboxcli  | createDirPatch  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by cnlangzi — APPROVED** [review]

**Pull request merged**
