### PR TITLE
Fix/fees table

### PR DESCRIPTION
**Pull request by dabasov**

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/fees-table  |
| gosdk  | fix/fees-table  |
| zboxcli  | staging  |
| zwalletcli  | fix/fees-table  |
| 0chain  | fix/fees-table  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/fees-table  |
| gosdk  | fix/fees-table  |
| zboxcli  | staging  |
| zwalletcli  | fix/fees-table  |
| 0chain  | fix/fees-table  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by stewartie4 — COMMENTED** [review]
happy to merge on green test run

**Comment by Kishan-Dhakan** [comment]
Should not be needed now as Multisig tests are skipped, closing this PR. @dabasov feel free to re-open this if needed.

**Pull request closed without merging**
