### PR TITLE
Fix tests for list

### PR DESCRIPTION
**Pull request by din-mukhammed**
Associated PRs:
- gosdk: https://github.com/0chain/gosdk/pull/1033
- zboxcli: https://github.com/0chain/zboxcli/pull/456/

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-june-5  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-july-1  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zboxcli  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zwalletcli  | sprint-july-1  |
| 0chain  | users/sunilmhta/fix/2544/0chain/blobber-settings  |
| blobber  | sprint-july-1  |
| authorizer  | sprint-july-1  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by Kishan-Dhakan — COMMENTED** [review]
GreaterOrEqual's should be Equals, correct? Merging this, please change it in a separate PR

**Review by Kishan-Dhakan — APPROVED** [review]

**Comment by Kishan-Dhakan** [comment]
Passing run: https://github.com/0chain/gosdk/actions/runs/5498950793

**Pull request merged**
