### PR TITLE
Add Sleep after upload 

### PR DESCRIPTION
**Pull request by Hitenjain14**
We need to wait for some time after uploading the file, so blobber can redeem the writemarker.

### CODE REVIEW

**Review by stewartie4 — COMMENTED** [review]
The tests above don't verify that the write marker has been redeemed so are these waits necessary? And why 16 seconds?

**Comment by Hitenjain14** [comment]
> The tests above don't verify that the write marker has been redeemed so are these waits necessary? And why 16 seconds?

These tests check if the amount has been deducted from the write pool or not on update, for this we check the difference between initial allocation and final allocation write pool. We have no control of when these write markers are redeemed, so we wait for 16 seconds for them to be redeemed so that the initial balance is of after the tokens has been deducted.

**Comment by Hitenjain14** [comment]
If u don't wait you can get a value of the write pool where no blobbers have redeemed the writemarker or 1 of them and soo on.

**Review by stewartie4 — APPROVED** [review]
Ok thanks for the tests update, happy to merge once they are passing

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
