### PR TITLE
Repair Allocation Tests

### PR DESCRIPTION
**Pull request by Hitenjain14**
https://github.com/0chain/blobber/pull/1114
https://github.com/0chain/gosdk/pull/1004
https://github.com/0chain/zs3server/pull/44
https://github.com/0chain/s3-migration/pull/70
https://github.com/0chain/zboxcli/pull/461

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | replace-api-test  |
| gosdk  | refactor/repair  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/fileMetaHash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | replace-api-test  |
| gosdk  | refactor/repair  |
| zboxcli  | fix/fileMetaHash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/fileMetaHash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]

**Review by stewartie4 — APPROVED** [review]
These look great, but we need CLI coverage too

**Review by stewartie4 — CHANGES_REQUESTED** [review]
Happy to approve once CLI coverage has been added

**Comment by Kishan-Dhakan** [comment]
Have to merge to sprint branch since https://github.com/0chain/gosdk/pull/1004 got merged. Added issue https://github.com/0chain/gosdk/pull/1004

**Pull request merged**
