### PR TITLE
Update zboxcli_upload_test.go

### PR DESCRIPTION
**Pull request by abouroumine**
Associated PRs (Link as appropriate):
- zbox: https://github.com/0chain/zboxcli/pull/192
- zwalelet:
- gosdk: https://github.com/0chain/gosdk/pull/416
- 0chain:
- blobber: https://github.com/0chain/blobber/pull/529

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blobber/issue-524  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blobber/issue-524  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blobber/issue-524  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by stewartie4 — APPROVED** [review]

**Review by peterlimg — APPROVED** [review]
lgtm

**Review by moldis — APPROVED** [review]

**Pull request merged**
