### PR TITLE
Fix/remove register

### PR DESCRIPTION
**Pull request by Jayashsatolia403**

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove-register  |
| gosdk  | staging  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove-register  |
| gosdk  | fix/remove-register  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | staging  |
| 0box  | fix/remove-register  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove-register  |
| gosdk  | fix/remove-register  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | fix/remove-register  |
| 0box  | fix/remove-register  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove-register  |
| gosdk  | fix/remove-register  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | fix/remove-register  |
| 0box  | fix/remove-register  |
| 0dns  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Pull request merged**
