### PR TITLE
Use client ID as stake pool id

### PR DESCRIPTION
**Pull request by peterlimg**
Update system tests about the zboxcli and zwalletcli commands to remove the `pool_id` param

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | one-pool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | one-pool  |
| zwalletcli  | one-pool  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | one-pool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | one-pool  |
| zwalletcli  | one-pool  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — CHANGES_REQUESTED** [review]
remove commented tests

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | one-pool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | one-pool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | one-pool  |
| zwalletcli  | one-pool  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | one-pool  |
| gosdk  | one-pool  |
| zboxcli  | one-pool  |
| zwalletcli  | one-pool  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
