### PR TITLE
s3 migration error tests

### PR DESCRIPTION
**Pull request by stewartie4**

### CODE REVIEW

**Review by Kishan-Dhakan — APPROVED** [review]
Great coverage, LGTM

**Comment by stewartie4** [comment]
all new tests passing

**Comment by Kishan-Dhakan** [comment]
"Should fail when bucket too large for allocation" fails on first try due to a missing file error (`open /root/.s3migration/s3/3855e05a941ee2a1c7bfd76864ec1135484ce0a764ecd3cb73b3cb0339549a1e: no such file or directory`), and passes on retry. Please investigate it and fix in a separate PR or create a new ticket, thanks

**Comment by Kishan-Dhakan** [comment]
Passing run: https://github.com/0chain/system_test/actions/runs/5034130237/jobs/9028770016?pr=678 (except crashes)

**Comment by stewartie4** [comment]
I'll look at this under the next ticket - i've been seeing this locally too, looks like a bug

**Pull request merged**
