### PR TITLE
delete testcase fix for partial delete.

### PR DESCRIPTION
**Pull request by princeparmar**
zbox: https://github.com/0chain/zboxcli/pull/185
gosdk: https://github.com/0chain/gosdk/pull/407

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | staging  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/406-partial-delete-support  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — COMMENTED** [review]
Happy to merge once tests Pass. This is fix is needed asap since all the flakiness from the suite has been effectively removed, only partial failure of delete cases causes fails sometimes. If you need any help please see: https://0chain.slack.com/archives/GREHVKQKS/p1644797353994499

**Comment by Kishan-Dhakan** [comment]
@princeparmar let me know your availability to discuss blockers in this PR. Please reach out to me slack, we need to get this in asap.

**Comment by princeparmar** [comment]
Let's connect after 8pm.

**Comment by cnlangzi** [comment]
it is fixed by https://github.com/0chain/system_test/pull/234

**Pull request closed without merging**
