### PR TITLE
fix download accounting test

### PR DESCRIPTION
**Pull request by lpoli**
This PR takes actual download cost calculation into consideration and tests for the reduced balance.

Related PR:
ZboxCli: https://github.com/0chain/zboxcli/pull/198
Issue: https://github.com/0chain/zboxcli/pull/198

### CODE REVIEW

**Review by Kishan-Dhakan — APPROVED** [review]

**Comment by Kishan-Dhakan** [comment]
Approved on temporary basis, will need to be re-done later.

**Comment by stewartie4** [comment]
Happy to approve, assuming calculations are correct 
Lint is failing on something annoying so if you don't want to re-run let me know

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/download-cost-calculation  |
| gosdk  | modify/read-marker  |
| zboxcli  | modify/read-marker  |
| zwalletcli  | staging  |
| 0chain  | modify/read-marker  |
| blobber  | modify/read-marker2  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/download-cost-calculation  |
| gosdk  | staging  |
| zboxcli  | fix/download-cost-calculation  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
