### PR TITLE
move, copy, delete directory tests #180

### PR DESCRIPTION
**Pull request by shalinikum**

### CODE REVIEW

**Comment by stewartie4** [comment]
@shalinikum this should point to sprint 1.10 not master

**Review by stewartie4 — COMMENTED** [review]
@shalinikum this has been in review for a long time, what's needed to get it across the line?

**Comment by shalinikum** [comment]
> @shalinikum this has been in review for a long time, what's needed to get it across the line?

Had issue with shared folder test. It's resolved now. Will push one more commit by today.

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM pending a full passing run

**Review by stewartie4 — APPROVED** [review]

**Comment by Kishan-Dhakan** [comment]
Passing run: https://github.com/0chain/system_test/actions/runs/6537276566/job/17756306909

**Pull request merged**
