### PR TITLE
re-open Stake pool update

### PR DESCRIPTION
**Pull request by stewartie4**
https://github.com/0chain/system_test/pull/162 was reverted from master because the tests were broken and the  consuming code was not ready to merge 
Re-open PR to merge once code is ready

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | stake_pool_update  |
| gosdk  | sp-changes  |
| zboxcli  | sp-changes  |
| zwalletcli  | staging  |
| 0chain  | sp_offers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | stake_pool_update  |
| gosdk  | sp-changes  |
| zboxcli  | sp-changes  |
| zwalletcli  | staging  |
| 0chain  | sp_offers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | stake_pool_update  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | sp-changes  |
| zwalletcli  | staging  |
| 0chain  | sp_offers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | stake_pool_update  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | sp-changes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | stake_pool_update  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | sp_offers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Sriep — APPROVED** [review]

**Review by Kishan-Dhakan — APPROVED** [review]

**Pull request merged**
