### PR TITLE
List file support

### PR DESCRIPTION
**Pull request by avanaur**
Resolves https://github.com/0chain/blobber/issues/699

Part of https://github.com/0chain/blobber/pull/730 and https://github.com/0chain/zboxcli/pull/267

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/list-file  |
| gosdk  | staging  |
| zboxcli  | feature/list-file  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/list-file  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/list-file  |
| gosdk  | staging  |
| zboxcli  | feature/list-file  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/list-file  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by stewartie4 — APPROVED** [review]
LGTM

**Review by peterlimg — APPROVED** [review]
lgtm

**Pull request merged**
