### PR TITLE
398 new system test for nft allocation features

### PR DESCRIPTION
**Pull request by Kishan-Dhakan**

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 828-nft-restrict-file-access-options  |
| authorizer  | staging  |
| 0box  | 828-nft-restrict-file-access-options  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by devyetii** [comment]
Successful run of this system tests branch [here](https://github.com/0chain/system_test/actions/runs/3774572155/jobs/6416727470)

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | staging  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by dabasov** [comment]
successful run https://github.com/0chain/0chain/actions/runs/4116598014/jobs/7106843538

**Pull request merged**
