### PR TITLE
Upgrade gosdk

### PR DESCRIPTION
**Pull request by lpoli**
This PR upgrades gosdk required for latest changes in gosdk and blobber

0chain PR: https://github.com/0chain/0chain/pull/1791
Blobber PR: https://github.com/0chain/blobber/pull/870
Gosdk PR: https://github.com/0chain/gosdk/pull/637
Zboxcli PR: https://github.com/0chain/zboxcli/pull/324

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]

**Comment by stewartie4** [comment]
closing as stalr

**Review by stewartie4 — COMMENTED** [review]
Is this PR still valid @lpoli ?

**Comment by lpoli** [comment]
> 

@stewartie4 Yes it still is.

**Review by stewartie4 — COMMENTED** [review]
no worries, what's the purpose of the upgrade? we don't use gosdk that much

**Comment by lpoli** [comment]
> no worries, what's the purpose of the upgrade? we don't use gosdk that much

If both blobber and gosdk has changes on operations that depend on each other then its necessary to upgrade gosdk.
The related PRs on blobber and gosdk has added fileID and fileMetaRoot in the file meta data of file.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | enhancement/modify-wm-for-gdpr  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | enhancement/modify-wm-for-gdpr  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | enhancement/modify-wm-for-gdpr  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | enhancement/modify-wm-for-gdpr  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
