### PR TITLE
modify initstorage sdk arguments

### PR DESCRIPTION
**Pull request by bisakhmondal**
Related to https://github.com/0chain/gosdk/pull/623

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | chain-fee-integration  |
| gosdk  | chain-fee  |
| zboxcli  | chain-fee  |
| zwalletcli  | feat/chain-fee  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Review by stewartie4 — APPROVED** [review]

**Review by stewartie4 — COMMENTED** [review]
Is this PR still valid? If I get no reply I will close in 24 hrs

**Comment by Kishan-Dhakan** [comment]
Closing as it is in progress at https://github.com/0chain/system_test/tree/chain-fee

**Pull request closed without merging**
