### PR TITLE
Remove attributes test and who-pays field

### PR DESCRIPTION
**Pull request by lpoli**
This PR remove system-test for attribute test and its related counterpart.

### CODE REVIEW

**Comment by lpoli** [comment]
@Kishan-Dhakan Please check for the .json and .hbs files in this PR and remove attributes fields.

**Review by dabasov — CHANGES_REQUESTED** [review]
please fix removed tests

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | fix/update-attributes  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | fix/update-attributes  |
| 0chain  | staging  |
| blobber  | fix/update-attributes  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by Kishan-Dhakan** [comment]
@lpoli I have remove the remaining attribute occurrences.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | fix/update-attributes  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | fix/update-attributes  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | fix/update-attributes  |
| 0chain  | staging  |
| blobber  | fix/update-attributes  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | fix/update-attributes  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | fix/update-attributes  |
| 0chain  | fix/update-attributes  |
| blobber  | fix/update-attributes  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | fix/update-attributes  |
| 0chain  | staging  |
| blobber  | fix/update-attributes  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
