### PR TITLE
Test for setting is_available field

### PR DESCRIPTION
**Pull request by Sriep**
0chain : https://github.com/0chain/0chain/pull/2247
- 0chain  https://github.com/0chain/0chain/pull/2271
- gosdk: https://github.com/0chain/gosdk/pull/866
- zboxcli: https://github.com/0chain/zboxcli/pull/398

### CODE REVIEW

**Review by Kishan-Dhakan — CHANGES_REQUESTED** [review]
@Sriep https://github.com/0chain/zboxcli/actions/runs/4607308438/jobs/8141662909 it failed, availability test is timing out. I suggest instead of
```
for i := range startBlobbers {
			setAvailability(t, startBlobbers[i].ID, false)
			t.Cleanup(func() { setAvailability(t, startBlobbers[i].ID, true) })
		}

```
setAvailability false for only 1 blobber, and then do

```
output, err = createNewAllocation(t, configPath, createParams(map[string]interface{}{
    "lock":   "0.5",
    "data":   3,
    "parity": 3,
}))
```
so allocation will need 6 blobbers, but 1 will not be available and you should get your error.

For bl-update, this is failing:
`require.Equal(t, newIsAvailable, finalBlobberInfo.IsAvailable)`
It is because in the test you are not updating it as part of this:
```
output, err = updateBlobberInfo(t, configPath, createParams(map[string]interface{}{"blobber_id": intialBlobberInfo.ID, "write_price": newWritePrice, "service_charge": newServiceCharge, "read_price": newReadPrice, "num_delegates": newNumberOfDelegates, "max_offer_duration": newMaxOfferDuration, "capacity": newCapacity, "min_lock_demand": newMinLockDemand, "min_stake": newMinStake, "max_stake": newMaxStake}))
		require.Nil(t, err, strings.Join(output, "\n"))
```
You need to update it as well

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | is_available  |
| gosdk  | staging  |
| zboxcli  | bl_update_is_available  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | is_available  |
| gosdk  | staging  |
| zboxcli  | bl_update_is_available  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
